### ISSUE TITLE
Iframe qui ne s'affiche pas

### ISSUE THREAD

**Issue by sachaandre** [osunyorg/admin#1227]
J'essaie d'ajouter une iframe sur ma page d'accueil d'un site proposant une mise en page d'un google agenda ( Styled Calendar )

Mon iframe ressemble à ça :
```
<iframe src="https://embed.styledcalendar.com/#82ak37vadFCNG647NeNu" title="Styled Calendar" class="styled-calendar-container" style="width: 100%; border: none;" data-cy="calendar-embed-iframe"></iframe>
<script async type="module" src="https://embed.styledcalendar.com/assets/parent-window.js"></script>
```

Et une fois mise elle me renvoie ces erreurs dans la console (avec Chrome) : 
```
Refused to load the script 'https://embed.styledcalendar.com/assets/parent-window.js' because it violates the following Content Security Policy directive: "default-src 'self' osuny-1b4da.kxcdn.com *.osuny.org osuny.s3.fr-par.scw.cloud calendar.google.com 'unsafe-inline'". Note that 'script-src-elem' was not explicitly set, so 'default-src' is used as a fallback.

Refused to frame 'https://embed.styledcalendar.com/' because it violates the following Content Security Policy directive: "default-src 'self' osuny-1b4da.kxcdn.com *.osuny.org osuny.s3.fr-par.scw.cloud calendar.google.com". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.
```

Quelque chose à voir avec la Content Security Policy qui m'empêche le chargement de certaines ressources. Est ce que je peux agir dessus, ou il s'agit de quelque chose à votre niveau, ou il faut que je cherche une autre solution concernant l'affichage de mon calendrier ? 

Bonne journée à vous !

**Comment by sachaandre** [comment]
Pour info, j'ai aussi testé avec Firefox et j'ai un message d'erreur console similaire : 
`Content-Security-Policy : Les paramètres de la page ont empêché le chargement d’une ressource à https://embed.styledcalendar.com/assets/parent-window.js (« default-src »).`
`Content-Security-Policy : Les paramètres de la page ont empêché le chargement d’une ressource à https://embed.styledcalendar.com/#82ak37vadFCNG647NeNu (« default-src »).`

**Comment by arnaudlevy** [comment]
C'est lié à l'ajout des CSP dans la https://github.com/noesya/osuny-hugo-theme-aaa/releases/tag/v4.0.3.
J'ai réenregistré le site, est-ce toujours bloqué ?

**Comment by sachaandre** [comment]
L'iframe s'affiche sans soucis ! 
Merci beaucoup !

**Comment by sachaandre** [comment]
Je commente à nouveau ici, j'ai une nouvelle iframe qui ne s'affiche pas sur mon site : https://sachaandre-lgvea.web.deuxfleurs.fr/

J'essaie ici d'utilier un service de création de mailing list (mailerlite) et le formulaire ne s'affiche pas correctement...

Est il possible d'avoir une liste prédéfinie plus élargie de service qu'on peut utiliser ? Sinon, y a t'il une liste préconisée par le réseau noseya de services qui seraient automatiquement acceptés dans les iframes ? 

Bonne journée et bonne fin d'année 🎉

**Comment by arnaudlevy** [comment]
Je crois que si tu enregistres le site ou si tu attends demain le nettoyage nocturne ça va marcher. On construit la liste blanche en fonction de l'usage

**Comment by arnaudlevy** [comment]
@SebouChu @pabois faudrait qu'on refresh à la volée non ?

**Comment by SebouChu** [comment]
Coucou @sachaandre !

Les CSP sont automatiquement mis à jour quand on ajoute une iframe dans un bloc, est-ce-que tu pourrais m'envoyer le code HTML que tu utilisais pour voir si c'était bien l'origine du problème ou si ça se situe ailleurs ?

**Comment by pabois** [comment]
@sachaandre pardon de t'embêter. Tu rencontres toujours le problème ?

**Comment by sachaandre** [comment]
Hello, j'ai enlevé le module donc je n'ai pas réessayé
Je vais recommencer sur mon blog personnel pour vior is je rencontre le problème

**Comment by arnaudlevy** [comment]
@sachaandre on close l'issue, tu nous dis si ça se reproduit ? Merci !
