### ISSUE TITLE
Ajout d'un composant de liste "Liens externes"

### ISSUE THREAD

**Issue by sachaandre** [osunyorg/admin#1229]
Je souhaiterais pouvoir ajouter sur ma page d'accueil un composant similaire à la capture d'écran ci-dessous avec une liste de liens externes (ressources externes)
<img width="1228" alt="Capture d’écran 2023-09-03 à 23 38 06" src="https://github.com/noesya/osuny/assets/14942470/f3f70106-f942-4097-a693-896a6c257c79">

J'imaginais utiliser quelque chose de similaire à la disposition "Cartes" du bloc Pages : 
<img width="508" alt="Capture d’écran 2023-09-03 à 23 42 03" src="https://github.com/noesya/osuny/assets/14942470/1037b441-3b4a-4e38-8aed-bae7f30e0296">

Est ce qu'il est possible d'ajouter un bloc de listes "Liens Externes" ?

**Comment by arnaudlevy** [comment]
On se dirige plutôt vers un bloc "Pages" capable de gérer les liens externes

**Comment by arnaudlevy** [comment]
Finalement, c'est bien un bloc Liens, et c'est fait !
