### ISSUE TITLE
Formation

### ISSUE THREAD

**Issue by arnaudlevy** [osunyorg/admin#1584]
- [x] Lien vers le site en plus du lien d'inscription ?
- [x] Logo de formation
- [x] But contrôlé par l'état -> bodyclass ?
- [ ] @violenn Inverser "Objectifs" et "En chiffres"
- [x] Inverser blocs et infos administratives

**Comment by arnaudlevy** [comment]
https://github.com/noesya/osuny/issues/1579

**Comment by arnaudlevy** [comment]
@Olivia206 j'ai été idiot, j'ai noté "Inverser", mais je sais pas le sens existant et le sens projeté, sorry

**Comment by arnaudlevy** [comment]
Le BUT contrôlé par l'état est une certification du diplôme

**Comment by Olivia206** [comment]
À quoi correspond "En chiffres" ? 

Et actuellement dans la présentation d'une formation on a : 
- infos de présentation
- blocs
- infos administratives

L'idée c'est que les blocs aillent en dernier ?

**Comment by arnaudlevy** [comment]
on ne peut pas entrelacer blocs et contenus Qualiopi, donc on reste à cette situation.
