### ISSUE TITLE
Possibilité de supprimer le document de synthèse téléchargeable - page formation

### ISSUE THREAD

**Issue by SophieLesaint** [osunyorg/admin#1632]
Lors d'une création de page formation, je télécharge un PDF dans le champ "document de synthèse téléchargeable".

Une fois la page créée et publiée, je me rends compte que le document téléchargé n'est pas le bon. Je ne souhaite pas le remplacer par un autre document mais je souhaite le supprimer. Je ne peux pas supprimer le document en ligne.

![Capture d’écran 2024-02-16 à 10 03 25](https://github.com/noesya/osuny/assets/5910978/da673494-9666-4d42-9017-1c68795b3607)

![Capture d’écran 2024-02-16 à 10 05 11](https://github.com/noesya/osuny/assets/5910978/daa1e3ac-f780-4df9-a89f-5040bffa20ef)

https://bordeaux-iut-de-bordeaux.web.deuxfleurs.fr/formations/carrieres-sociales/

**Comment by pabois** [comment]
@SophieLesaint pardon ça a été un peu long !
C'est corrigé. Il est maintenant possible de supprimer le fichier depuis le formulaire
