### ISSUE TITLE
Blocs "coûts" des formations ne s'affichent pas en front

### ISSUE THREAD

**Issue by SophieLesaint** [osunyorg/admin#1682]
IUT de Bordeaux
Pour les formations : les blocs liés aux coûts sont renseignés dans le back office mais ne s'affichent pas en front

Exemple : 
https://bordeaux-iut-de-bordeaux.web.deuxfleurs.fr/formations/management-de-la-logistique-et-des-transports/

![Capture d’écran 2024-03-04 à 17 17 45](https://github.com/noesya/osuny/assets/5910978/7736e037-3e21-4d71-9242-3228ec3ff714)

**Comment by Olivia206** [comment]
Merci, les champs s'affichent maintenant bien
