### ISSUE TITLE
Bodyclass et ancestors

### ISSUE THREAD

**Issue by alexisben** [osunyorg/admin#1718]
@Clararigaud a relevé sur le thème :

> Si je met deux classes sur une page parente ex: "classe-1 classe-2", le prefix ancestor ne s'applique que sur la premiere classe dans les pages enfants: "ancestor-classe-1 classe-2"
Je propose "ancestor-classe-1 ancestor-classe-2"

**Comment by Clararigaud** [comment]
C’est surtout une question de cohérence :) si le comportement s’applique sur la premiere classe parente pourquoi ps sur la seconde ?
