### ISSUE TITLE
Formations : bug suppression formation "parent" qui a des formations "parcours"

### ISSUE THREAD

**Issue by SophieLesaint** [osunyorg/admin#1740]
Sur IUT Bdx

Suppression d'une formation "parent" (BUT Génie Biologique) qui avait 3 formations "parcours" avec des blocs hérités

La formation parent a disparu du BO et du front
Les 3 formations parcours ont disparus du BO mais sont toujours disponibles en front avec des bug (telechargement plaquette)

- https://bordeaux-iut-de-bordeaux.web.deuxfleurs.fr/formations/parcours-agronomie/
- https://bordeaux-iut-de-bordeaux.web.deuxfleurs.fr/formations/parcours-dietetique-et-nutrition/
- https://bordeaux-iut-de-bordeaux.web.deuxfleurs.fr/formations/parcours-sciences-de-laliment-et-biotechnologie/

2 points :

1. Il faut prévenir l'utilisateur que la suppression d'une formation parent va entrainer la suppression des formations parcours qui en dépendent
2. Il faut que les formations supprimées disparaissent du front

**Comment by arnaudlevy** [comment]
Merci @SophieLesaint !

**Comment by pabois** [comment]
Les formations ne sont plus supprimées en cascade à présent. Elles sont redescendues d'un niveau (donc généralement au niveau racine).

**Comment by pabois** [comment]
Quand une formation est supprimée normalement elle disparait du front
