### ISSUE TITLE
Repo qui perd son token

### ISSUE THREAD

**Issue by arnaudlevy** [osunyorg/admin#1751]
Il est là... Il est plus là.
Pb de fail Github ?
Est-ce lié aux fichiers qui ne sont pas correctement supprimés ?

**Comment by pabois** [comment]
Comme expliqué hier sur Slack, je pense que c'est lié à la mécanique qui fait que si ça fail trop de fois l'accès à GH on envoie un mail aux admins et on enlève le token pour éviter que ça boucle

**Comment by pabois** [comment]
tu es superadmin, pas admin

**Comment by arnaudlevy** [comment]
ah
C'est logique qu'on les reçoive pas ?
