### ISSUE TITLE
Categories d'evenements /  identifiant formation 

### ISSUE THREAD

**Issue by Clararigaud** [osunyorg/admin#1797]
L'*identifiant de la formation* et le *slug de la categorie d'evenement* sont editable + ne sont pas mis à jour automatiquement on dirait. 

Bref problème dont la conséquence est les deux ne coincident pas toujours. Ce qui est important pour l'affichage des events correspondant à une formation

**Comment by arnaudlevy** [comment]
ça doit se faire en automatique, ça.
@Clararigaud tu peux remettre le contexte, qu'on vérifie si c'est bien réglé stp ?

**Comment by Clararigaud** [comment]
C'était dans le cas de MJ, ou on lie les categories d'evenements à des formations: 

Extrait de la solution que j'avais envoyé, mais je me demande si il ne faudrait pas bloquer la possibilité d'editer. 

'' pour faire apparaitre la prochaine session dans le haut de la page formation correspondante on compare l'identifiant de la formation avec la catégorie de l’évènement. Dans la cas de session équipe juridique, les deux n'étaient pas nommés pareil. 

Si ça se reproduit : s'assurer que l'identifiant de la formation 
Tableau de bord > Enseignement > Formations > Master Class Greenwashing - Session équipes jur... > Modifier [] Identifiant
est le même que le slug de la catégorie
Tableau de bord > Communication > Sites Web > Master Class > Agenda > Catégories > Master Class Greenwashing - Session équipes jur... > Modifier [] Slug
''
