### ISSUE TITLE
Espace entre parenthèses qui disparaît

### ISSUE THREAD

**Issue by Olivia206** [osunyorg/admin#1802]
Retour de la criée : "lorsque des dates sont dans des parenthèses, il n'y a pas d'espace après la virgule même si elle est mise dans le bloc chapitre (cf[ page Archives/artistes,…](https://lacriee-site.web.deuxfleurs.fr/fr/ressources/archives/artistes-autrices-auteurs-commissaires-etc/))"

Dans le back on a bien un espace entre 2000 et 2006 : 
![Capture d’écran 2024-04-15 à 15 58 04](https://github.com/osunyorg/admin/assets/91660674/a43ff326-36ef-4a4e-94a3-cb45e3c9869a)

Mais le static renvoie ça : 
`
    data:
      layout: no_background
      text: >-
        <p>-- Adel Abdessemed ((2000,2006))<br>-- Absalon ((2001))<br>-- Scoli Acosta ((2014))<br>-- Bas Jan Ader ((2016))<br>-- Anna Margarita Albelo ((2006))<br>-- Dove Allouche ((2019))<br>-- Basma  Alsharif ((2019))<br>-- Francis Alÿs ((2014))<br>-- Gilles Amalvi ((2019))<br>-- Cyrille André ((2010))<br>-- Jean-Baptiste André ((2017))<br>-- Ziad Antar ((2013,2014))<br>-- Eleanor Antin ((2017))<br>-- David Antin ((2017))<br>-- Radoš Antonijević ((2013))<br>-- Pierre Ardouvin ((2018))<br>-- Isabelle  Arthuis ((2009,2022,2023))<br>-- Artists’Campaign to Repeal the Eighth Amendment ((2019))<br>-- Félicia Atkinson ((2017))<br>-- Charles Atlas ((2002))<br>-- Kader Attia ((2003))<br>-- Véronique Aubouy ((2009))<br>-- Simon Augade ((2015))<br>-- Damir Avdić (2013))</p>`

**Comment by arnaudlevy** [comment]
Problème avec Orthotypo probablement

**Comment by arnaudlevy** [comment]
Il n'y a plus Orthotypo, maintenant il y a LanguageTool
