### ISSUE TITLE
Ajout de structure / de sémantique dans la partie "contacts" d'une formation

### ISSUE THREAD

**Issue by Clararigaud** [osunyorg/admin#1808]
Ça serait bien de pouvoir ajouter une structure aux contacts plutôt qu'un simple champ html.
Par exemple j'ai besoin d'avoir un seul contact avec nom, telephone et email dans ce cas là: 
![image](https://github.com/osunyorg/admin/assets/2864241/8c648dad-fe14-4fca-a071-c8c0e1ecd865)

**Comment by arnaudlevy** [comment]
Prendre le premier rôle
