### ISSUE TITLE
Problème avec une organisation manquante

### ISSUE THREAD

**Issue by arnaudlevy** [osunyorg/admin#1816]
<img width="1792" alt="Capture d’écran 2024-04-17 à 16 29 09" src="https://github.com/osunyorg/admin/assets/2088968/7011a85d-b220-4d0a-8c2d-d60bb18a7cde">

https://www.reseauexcellence.fr/fr/reseau-excellence-en-france/reseau-excellence-bretagne/

Cette organisation n'y est pas
https://epv.osuny.org/admin/university/organizations/e7b3354c-0a03-4a32-bd56-70055f3d70b0

**Comment by SebouChu** [comment]
L'orga n'était pas dans le bloc, mais le bloc ciblera bientôt la catégorie directement
