### ISSUE TITLE
Les événements passés (archive) disparaissent des données des blocks où ils étaient sélectionnés

### ISSUE THREAD

**Issue by alexisben** [osunyorg/admin#1859]
Pourquoi un événement listé dans un bloc agenda disparaît s'il est passé ? Je crois que ce n'est pas correct.

**Comment by arnaudlevy** [comment]
Si le block est paramétré sur les événements futurs et à venir, il disparaît quand il passe.
Inversement, s'il est sur les archives, il apparaît quand il passe.

![Uploading Capture d’écran 2024-05-07 à 21.02.46.png…]()
