### ISSUE TITLE
Amélioration orthotypo

### ISSUE THREAD

**Issue by justinpuyo** [osunyorg/admin#1877]
La correction automatique orthotypo amène à des erreurs dans certains cas.

Préférer une analyse à la demande qui propose des corrections plutôt que les imposer. Par exemple un bouton sur les champs de texte.
Ce qui serait parfait c'est d'ajouter un aspect didactique : afficher les règles qui sont appliquées par les corrections proposées.

**Comment by arnaudlevy** [comment]
On a fait avec LanguageTool !
On va ajouter un bouton pour le lancer, là c'est trop gourmand en requêtes.
