### ISSUE TITLE
Calcul du weight dans les statics d'event

### ISSUE THREAD

**Issue by SebouChu** [osunyorg/admin#1880]
Actuellement, chaque jour passé change le weight et donc le static. Il faut une valeur constante

cf https://github.com/osunyorg/lacriee-site/commit/a822009cada851d1be8146247590ffab03a436a1

**Comment by arnaudlevy** [comment]
Attention les événements s'éloignent toujours !

Dans le futur, c'est date ascendante (du passé au futur) pour avoir les événements les plus proches d'abord.

Dans le passé, c'est date descendante (du futur au passé) pour avoir les vieilles archives sur les pages profondes et les archives récentes en première page.

**Comment by arnaudlevy** [comment]
Je crois qu'on peut peut-être faire avec les dates pour les archives, pas de weight. J'essaie.

**Comment by arnaudlevy** [comment]
ok si on a une date et pas de weight pour les archives ça marche. Je code ça.
