### ISSUE TITLE
NoMethodError in Importers::AlumniCohorts.execute

### ISSUE THREAD

**Issue by SebouChu** [osunyorg/admin#1892]
## Error in Osuny

**NoMethodError** in **Importers::AlumniCohorts.execute**
undefined method `first_name=' for nil

      person.first_name = @first_name
            ^^^^^^^^^^^^^

[View on Bugsnag](https://app.bugsnag.com/noesya-1/osuny/errors/664a0ff1d7588d0007a22f44?event_id=664a0ff100ed308b00300000&i=gh&m=ci)

## Stacktrace

    app/services/importers/hash_to_person.rb:64 - build_person
    app/services/importers/hash_to_alumnus.rb:6 - person
    app/services/importers/hash_to_person.rb:17 - valid?
    app/services/importers/hash_to_person.rb:8 - initialize
    app/services/importers/alumni_cohorts.rb:7 - new
    app/services/importers/alumni_cohorts.rb:7 - analyze_hash
    app/services/importers/base.rb:32 - block in analyze_xlsx
    app/services/importers/base.rb:30 - with_index
    app/services/importers/base.rb:30 - analyze_xlsx
    app/services/importers/base.rb:11 - initialize
    app/services/importers/base.rb:4 - new
    app/services/importers/base.rb:4 - execute
    bin/bundle:113 - load
    bin/bundle:113 - <main>

[View full stacktrace](https://app.bugsnag.com/noesya-1/osuny/errors/664a0ff1d7588d0007a22f44?event_id=664a0ff100ed308b00300000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by arnaudlevy** [comment]
Le fichier d'exemple est faux (manque Mastodon), et je pense qu'il faut mettre école, formation et année au tout début

**Comment by SebouChu** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**NoMethodError** in **Importers::AlumniCohorts.execute**](https://app.bugsnag.com/noesya-1/osuny/errors/664a0ff1d7588d0007a22f44?event_id=664a146400ed3880c5710000&i=gh&m=fx)
