### ISSUE TITLE
Footer: pouvoir ajouter un menu organisations ?

### ISSUE THREAD

**Issue by Clararigaud** [osunyorg/admin#1948]
Ça revient à chaque fois d'ajouter des logos de partenaires, sponsors, dans le footer.
On finit par faire un override du footer à chaque fois.
On peut ajouter un genre de menu qui vient se mettre dans le footer et qui permet de sélectionner des organisations (leur logo) ?

**Comment by arnaudlevy** [comment]
Duplicate https://github.com/osunyorg/admin/issues/2013
