### ISSUE TITLE
Octokit::NotFound in Communication::Website::UpdateThemeVersionJob@elephant

### ISSUE THREAD

**Issue by SebouChu** [osunyorg/admin#1975]
## Error in Osuny

**Octokit::NotFound** in **Communication::Website::UpdateThemeVersionJob@elephant**
GET https://api.github.com/repos/florimondmanca/osuny-test: 404 - Not Found // See: https://docs.github.com/rest/repos/repos#get-a-repository

[View on Bugsnag](https://app.bugsnag.com/noesya-1/osuny/errors/6659fcce379054000841694c?event_id=6659fcce00ee54be98e30000&i=gh&m=ci)

## Stacktrace

    app/services/git/providers/github.rb:144 - default_branch
    app/services/git/providers/github.rb:148 - branch_sha
    app/services/git/providers/github.rb:175 - tree
    app/services/git/providers/github.rb:162 - tree_items_by_path
    app/services/git/providers/github.rb:156 - tree_item_at_path
    app/services/git/providers/github.rb:110 - git_sha
    app/services/git/providers/github.rb:49 - update_theme
    app/services/git/repository.rb:31 - update_theme_version!
    app/models/communication/website/with_git_repository.rb:88 - update_theme_version_safely
    app/jobs/communication/website/update_theme_version_job.rb:3 - execute
    app/jobs/communication/website/base_job.rb:28 - perform

[View full stacktrace](https://app.bugsnag.com/noesya-1/osuny/errors/6659fcce379054000841694c?event_id=6659fcce00ee54be98e30000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by arnaudlevy** [comment]
@SebouChu Ça devrait pas être une souris ça ?

**Comment by SebouChu** [comment]
@arnaudlevy si
