### ISSUE TITLE
Robustesse Object Storage Scaleway

### ISSUE THREAD

**Issue by arnaudlevy** [osunyorg/admin#2008]
Il faut :  
- [ ] pouvoir rétablir un objet supprimé
- [ ] pouvoir reconstituer l'ensemble des objets en cas de défaillance Scaleway

Le premier cas est peut-être gérable avec du versioning de bucket : à tester.

Le second cas nécessite une copie write only vers une infra physique différente, soit en direct soit en tâche nocturne.
OVH propose un service S3 compatible.

**Comment by arnaudlevy** [comment]
Autre pb à régler, certains objets n'ont pas été passés en classe Standard, ils sont donc encore stockés sur une seule zone.

**Comment by arnaudlevy** [comment]
J'ai activé pour test le versioning sur le bucket de staging

**Comment by arnaudlevy** [comment]
https://www.scaleway.com/en/docs/storage/object/how-to/use-bucket-versioning/
https://www.scaleway.com/en/docs/tutorials/backup-dedicated-server-s3-duplicity/
https://www.scaleway.com/en/docs/tutorials/veeam-backup-replication-s3/

**Comment by SebouChu** [comment]
Le versioning ne gère pas le cas de suppression d'un objet car il n'est plus listé dans les objets. Cela ne gère que les overwrites.

**Comment by arnaudlevy** [comment]
Il faut alors mettre en place un write only qqpart

**Comment by arnaudlevy** [comment]
@SebouChu a fait un backup hebdomadaire
