### ISSUE TITLE
Ajustements i18n

### ISSUE THREAD

**Issue by pabois** [osunyorg/admin#2009]
- [x] mettre en place la liste des langues disponibles au niveau de l'université
- [x] index des objets (par exemple personnes) ou on peut switcher d'une langue à l'autre. On affiche en "normal" toutes les personnes qui sont disponibles dans la langue d'affichage (master = langue d'affichage ou master != langue & traduction déjà créée). On affiche en "grisé" les personnes non-encore disponibles dans la langue d'affichage. Un clic sur ces personnes créé la traduction dans la langue d'affichage
- [x] dans un post (par exemple) lorsqu'on choisit un auteur on a la liste complète des person (y compris celles non disponibles dans la langue d'affichage). On doit indiquer que l'auteur est publié ou non dans la langue d'affichage. Si l'auteur est non publié il serait idéal que le post indique l'auteur sans qu'il soit cliquable (puisque la fiche auteur n'est pas disponible). Si l'auteur existe dans la langue du post on affiche son nom dans cette langue. Sinon on affiche son nom dans la langue "master"
- [x] quand on créée une nouvelle personne on la créé en master dans la langue actuelle d'affichage 
- [x]  si la personne qu'on essaie de créer existe déjà (dans la langue en question ou dans une autre langue) il faut proposer de matcher
- [x] dans les choix de personne, il faut transformer les "select" en popins
- [x] considérer en interface qu'une personne non "créée" en russe n'est pas "publiée" en russe

**Comment by arnaudlevy** [comment]
https://github.com/osunyorg/admin/pull/2025

**Comment by arnaudlevy** [comment]
@pabois all good?
