### ISSUE TITLE
ActionView::Template::Error in server/universities#show

### ISSUE THREAD

**Issue by SebouChu** [osunyorg/admin#2011]
## Error in Osuny

**ActionView::Template::Error** in **server/universities#show**
Object must be a Date, DateTime or Time object. nil given.

[View on Bugsnag](https://app.bugsnag.com/noesya-1/osuny/errors/666701c22a1e11000833725f?event_id=666701c200ee68928df60000&i=gh&m=ci)

## Stacktrace

    app/views/server/universities/show.html.erb:24 - _app_views_server_universities_show_html_erb__2521877976125866475_1193200
    app/controllers/application_controller/with_locale.rb:19 - switch_locale

[View full stacktrace](https://app.bugsnag.com/noesya-1/osuny/errors/666701c22a1e11000833725f?event_id=666701c200ee68928df60000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by arnaudlevy** [comment]
Montant de contribution renseigné, mais sans date
