### ISSUE TITLE
Errno::EADDRNOTAVAIL in admin/university/organizations#in_language

### ISSUE THREAD

**Issue by SebouChu** [osunyorg/admin#2098]
## Error in Osuny

**Errno::EADDRNOTAVAIL** in **admin/university/organizations#in_language**
Failed to open TCP connection to nominatim.openstreetmap.org:443 (Cannot assign requested address - connect(2) for "nominatim.openstreetmap.org" port 443)

[View on Bugsnag](https://app.bugsnag.com/noesya-1/osuny/errors/66912fb57117910009756501?event_id=66912fb400efcf7e39640000&i=gh&m=ci)

## Stacktrace

    app/models/concerns/translatable.rb:84 - translate!
    app/models/concerns/translatable.rb:33 - find_or_translate!
    app/controllers/admin/university/organizations_controller.rb:47 - in_language
    app/controllers/application_controller/with_locale.rb:19 - switch_locale

[View full stacktrace](https://app.bugsnag.com/noesya-1/osuny/errors/66912fb57117910009756501?event_id=66912fb400efcf7e39640000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by arnaudlevy** [comment]
https://github.com/osunyorg/admin/issues/2099

**Comment by SebouChu** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Errno::EADDRNOTAVAIL** in **admin/university/organizations#in_language**](https://app.bugsnag.com/noesya-1/osuny/errors/66912fb57117910009756501?event_id=669137a200f3aa2cb6650000&i=gh&m=ra)
