### ISSUE TITLE
Errno::EADDRNOTAVAIL in admin/university/organizations#create

### ISSUE THREAD

**Issue by SebouChu** [osunyorg/admin#2099]
## Error in Osuny

**Errno::EADDRNOTAVAIL** in **admin/university/organizations#create**
Failed to open TCP connection to nominatim.openstreetmap.org:443 (Cannot assign requested address - connect(2) for "nominatim.openstreetmap.org" port 443)

[View on Bugsnag](https://app.bugsnag.com/noesya-1/osuny/errors/66913085ac9ebb00093b7e51?event_id=6691308500efc075cc110000&i=gh&m=ci)

## Stacktrace

    app/controllers/admin/university/organizations_controller.rb:75 - create
    app/controllers/application_controller/with_locale.rb:19 - switch_locale

[View full stacktrace](https://app.bugsnag.com/noesya-1/osuny/errors/66913085ac9ebb00093b7e51?event_id=6691308500efc075cc110000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by arnaudlevy** [comment]
Eu la personne au téléphone, à la création d'une orga ou à la traduction d'une autre orga, erreur.
Puis qqs mns après, ok.

Passer la géolocalisation en background job ?

**Comment by arnaudlevy** [comment]
"Le Grand Lemps" cause un crash
