### ISSUE TITLE
Ecran de MFA champ énorme

### ISSUE THREAD

**Issue by pabois** [osunyorg/admin#2140]
<img width="595" alt="Capture d’écran 2024-08-19 à 09 58 06" src="https://github.com/user-attachments/assets/956b41c6-86d5-462f-bb0f-4f80f9326434">

**Comment by arnaudlevy** [comment]
C'est pas que c'est énorme, mais il faudrait que ce soit moins moche (tout en gardant le grand champ).
Peut-être mettre les liens en bas en boutons côte à côte ?

**Comment by arnaudlevy** [comment]
![Capture d’écran 2024-08-22 à 18 16 41](https://github.com/user-attachments/assets/b9faf20e-61e4-4bc8-a653-d8b5fc0bc3b0)
