### ISSUE TITLE
Diplome generation automatique du shortname en fonction du type de diplome

### ISSUE THREAD

**Issue by Clararigaud** [osunyorg/admin#2178]
On avait évoqué ça @arnaudlevy , avoir une liste de diplômes correspondant à la liste des logos diplôme certifié. 
<img width="922" alt="image" src="https://github.com/user-attachments/assets/f81b0687-8634-41b3-98ae-821982ed3fc6">

Peut être le choix des deux :
pour par exemple
-  Licence -- > DNL ( mais affichage du nom "L") 
- Doctorat ---> DND ( mais on peut choisir d'afficher PhD) 

Important pour PR > https://github.com/osunyorg/theme/pull/541

**Comment by arnaudlevy** [comment]
J'ai fait une propriété explicite dans le static du diplôme : 

```yaml
certification: BUT
```

C'est vide quand il n'y en a pas.
@Olivia206 tu pourras reprendre cette donnée quand elle sera merged, et enlever le code de @Clararigaud qui s'appuie sur les short names stp ?
