### ISSUE TITLE
Bug interface édition SSO

### ISSUE THREAD

**Issue by pabois** [osunyorg/admin#2218]
quand on coche "A un SSO?" et qu'on ajoute du mapping, le select est disabled

**Comment by pabois** [comment]
C'est lié a une interaction pourrie avec le js de "conditional".
J'enlève du conditional le disabled/undisabled des select, parce que je ne vois pas de raison de disabled complètement.
Je suppose que le disabled avait pour raison de ne pas envoyer la valeur du champ "masqué" lors de la soumission du formulaire mais ça me parait peu judicieux

**Comment by arnaudlevy** [comment]
La modif du JS casse ailleurs (réglages d'un site)
