### ISSUE TITLE
Bug interface Page Equipe

### ISSUE THREAD

**Issue by SebouChu** [osunyorg/admin#2219]
Sur la page spéciale Equipe, on a un souci de z-index dans la recherche des personnes

<img width="465" alt="image" src="https://github.com/user-attachments/assets/2a56423e-1ac2-4b29-bff6-657bccc9a63e">

**Comment by arnaudlevy** [comment]
Je n'arrive plus à reproduire @SebouChu

**Comment by SebouChu** [comment]
@arnaudlevy t'as dû le régler avec tes modifs de style pour l'offcanvas des blocs
