### ISSUE TITLE
ActiveRecord::RecordInvalid in admin/research/researchers#sync_with_hal

### ISSUE THREAD

**Issue by SebouChu** [osunyorg/admin#2222]
## Error in Osuny

**ActiveRecord::RecordInvalid** in **admin/research/researchers#sync_with_hal**
La validation a échoué : Identifiant doit être rempli(e), Identifiant ne peut contenir que des lettres minuscules, des chiffres et des traits d'union.

[View on Bugsnag](https://app.bugsnag.com/noesya-1/osuny/errors/66f85f040bc83505e06ae749?event_id=66f85f0300f881dfb7ff0000&i=gh&m=ci)

## Stacktrace

    app/models/research/hal/author.rb:73 - block in import_research_hal_publications!
    app/models/research/hal/author.rb:72 - each
    app/models/research/hal/author.rb:72 - import_research_hal_publications!
    app/models/university/person/with_research.rb:40 - block in import_research_hal_publications!
    app/models/university/person/with_research.rb:38 - import_research_hal_publications!
    app/controllers/admin/research/researchers_controller.rb:27 - sync_with_hal
    app/controllers/application_controller/with_locale.rb:19 - switch_locale

[View full stacktrace](https://app.bugsnag.com/noesya-1/osuny/errors/66f85f040bc83505e06ae749?event_id=66f85f0300f881dfb7ff0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by SebouChu** [comment]
An error linked to this issue has been reopened in Bugsnag
[**ActiveRecord::RecordInvalid** in **admin/research/researchers#sync_with_hal**](https://app.bugsnag.com/noesya-1/osuny/errors/66f85f040bc83505e06ae749?event_id=66fc044a01000c42d8750000&i=gh&m=ra)

**Comment by arnaudlevy** [comment]
Pb avec une publi de Carlo Vercellone, Paris 8

**Comment by SebouChu** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**ActiveRecord::RecordInvalid** in **admin/research/researchers#sync_with_hal**](https://app.bugsnag.com/noesya-1/osuny/errors/66f85f040bc83505e06ae749?event_id=66fe5d2e00f8861c9ec60000&i=gh&m=fx)
