### ISSUE TITLE
NoMethodError in admin/communication/websites/posts#duplicate

### ISSUE THREAD

**Issue by SebouChu** [osunyorg/admin#2260]
## Error in Osuny

**NoMethodError** in **admin/communication/websites/posts#duplicate**
undefined method `title' for an instance of Communication::Website::Post

[View on Bugsnag](https://app.bugsnag.com/noesya-1/osuny/errors/66fbc35d0bc83505e072dd8e?event_id=66fbc35d00f8849b576b0000&i=gh&m=ci)

## Stacktrace

    app/models/concerns/with_duplication.rb:16 - duplicate_instance
    app/models/concerns/with_duplication.rb:5 - duplicate
    app/controllers/admin/communication/websites/posts_controller.rb:85 - duplicate
    app/controllers/application_controller/with_locale.rb:19 - switch_locale

[View full stacktrace](https://app.bugsnag.com/noesya-1/osuny/errors/66fbc35d0bc83505e072dd8e?event_id=66fbc35d00f8849b576b0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by arnaudlevy** [comment]
https://github.com/osunyorg/admin/pull/2262
