### ISSUE TITLE
Harmoniser les données relatives aux numéros de téléphone

### ISSUE THREAD

**Issue by Olivia206** [osunyorg/admin#2303]
Pour une personne, on reçoit des données comme ceci : 
```
phome_number:
    label: +0000
    value: tel:+0000
```

Ailleurs on a que le numéro : 
- bloc contact
- téléphone d'une école

C'est en front qu'on met "tel:xxx", on ne reçoit que le numéro brut.

**Comment by arnaudlevy** [comment]
- [ ] Utiliser les contact details
- [ ] Mettre sous test
- [ ] Supprimer les anciens helpers
