### ISSUE TITLE
Les blocs disparaissent après l'ajout d'un nouveau

### ISSUE THREAD

**Issue by justinpuyo** [osunyorg/admin#2304]
Quand on ajoute un nouveau bloc sur une page, les blocs disparaissent après avoir cliqué sur "Enregistrer".
Il faut rafraichir la page pour les faire apparaitre.
Le problème ne se pose pas lorsqu'on édite un bloc existant.

Il manque aussi un peu d'espace en bas de la fenêtre "Édition de bloc", le bandeau cache à moitié "Réglages avancés"

![Capture d’écran 2024-10-10 à 09 43 25](https://github.com/user-attachments/assets/28af5d5d-4f5a-4e0b-9e18-cb01c5db5c6b)

**Comment by arnaudlevy** [comment]
@SebouChu une histoire de JS ?

**Comment by justinpuyo** [comment]
Il me semble que @SebouChu a réglé ça l'autre jour. À confirmer.

**Comment by SebouChu** [comment]
Yes c'est corrigé, j'ai oublié de la noter comme closed !
