### ISSUE TITLE
ffmpeg nécessaire ?

### ISSUE THREAD

**Issue by SebouChu** [osunyorg/admin#2334]
Sur Osuny, on privilégie les URLs vers des vidéos hébergées (YouTube, Vimeo, Peertube, ...) par rapport à l'upload de vidéos sur le back-office. De cette base-là, on peut questionner l'utilité de `ffmpeg` utile dans 2 contextes :
- génération d'une image de preview
- analyse d'un blob vidéo pour avoir des informations telles que dimensions de l'image, durée, présence de pistes vidéo et audio)

Etat dans les environnements :
- Staging : aucun blob de type vidéo
- Prod : 11 blobs de type vidéo, qui ne semblent plus utilisés

**Potentiel gain de 256 Mo sur l'image de l'application**

<img width="658" alt="Capture d’écran 2024-10-16 à 13 17 30" src="https://github.com/user-attachments/assets/825ed1b8-e404-4c3c-b3fe-fbd8fbb2b273">

**Comment by arnaudlevy** [comment]
Tu as raison ce n'est pas utile on ne traite aucune vidéo, en revanche on a des fichiers audio

**Comment by SebouChu** [comment]
Bien vu, bon du coup on garde !

**Comment by SebouChu** [comment]
Ah alors attends, parce qu'on a des fichiers audio, mais on n'a pas l'air d'utiliser les metadatas

**Comment by arnaudlevy** [comment]
je ne crois pas non
