### ISSUE TITLE
Données d'une personne : champ "person"

### ISSUE THREAD

**Issue by Olivia206** [osunyorg/admin#2380]
Est-il envisageable d'uniformiser les personnes, entre une personne classique, une personne chercheuse, etc ?

Car dans les researchers/teachers on récupère ceci : 
```
person: >-
  Arnaud Levy
first_name: >-
  Arnaud
last_name: >-
  Levy
```
Mais si je ne me trompe pas pas dans une personne classique

Or ça pose un souci d'uniformité, visible ici : 

- Ici c'est ok
![Capture d’écran 2024-10-28 à 17 17 57](https://github.com/user-attachments/assets/ccdc4771-5fe1-41cf-b551-ca71ddf6f020)

- ici on ne prend pas la valeur (je n'avais pas remarqué ce pb, désolée !!)
![Capture d’écran 2024-10-28 à 17 18 01](https://github.com/user-attachments/assets/a1e3a1b4-2195-405b-9be2-3ebfb9814dc4)

Est-ce à nous de nous adapter, ou peut-on recevoir cette donnée dans le statique ?

**Comment by arnaudlevy** [comment]
Pas de pb !
Il faudrait quoi partout ?

**Comment by Olivia206** [comment]
Au moins `person`, on n'utilise nulle part first/last name, mais si on garde un "au cas où" alors ces 2 champs aussi !
