### ISSUE TITLE
Affichage des multiples auteurs et autrices dans les posts

### ISSUE THREAD

**Issue by Olivia206** [osunyorg/admin#2405]
On aurait besoin pour les signatures (https://github.com/osunyorg/theme/pull/715) de récupérer les datas de chaque auteurs ou autrice, ça évitera aussi de faire des listes à rallonge (exemple sur encommun revue)

Je ne sais pas où ça se situe dans vos priorités ceci dit !

**Comment by arnaudlevy** [comment]
https://github.com/osunyorg/admin/pull/2406

**Comment by arnaudlevy** [comment]
@Olivia206 tu veux les auteurs multiples, et aussi les données de la personne pour éviter de charger l'objet ?

**Comment by Olivia206** [comment]
Il me semble que ça permettrait effectivement d'alléger les partials !
Tu en penses quoi @alexisben ?

**Comment by arnaudlevy** [comment]
si c'est pas chiant je préfère fournir juste l'identifiant et éviter la dénormalisation, je crois
