### ISSUE TITLE
Module a11y

### ISSUE THREAD

**Issue by yuna-orsini** [osunyorg/admin#457]
<img width="379" alt="Capture d’écran 2022-06-23 à 22 55 58" src="https://user-images.githubusercontent.com/41020624/175398377-c7a9df93-1bef-46bd-b84f-ac8f008a6772.png">

Je ne suis probablement pas core-user de la solution Osuny mais quand je vois ce statut, je me pose la question de "sur quelle base d'audit ? comment ça fonctionne ? quelle valeur ça a ?". Ajouter un lien explicatif ? une mention ?

<img width="135" alt="Capture d’écran 2022-06-23 à 22 59 01" src="https://user-images.githubusercontent.com/41020624/175398747-a528e0b7-9160-4ea6-9c07-3a091a66eb77.png">

Je ne sais pas si la pastille verte est censée dire "ok, c'est accessible" mais une règle importante d'accessibilité est de ne pas transmettre une information uniquement par la couleur. Un petit label serait bienvenu pour expliciter le statut je pense.

**Comment by pabois** [comment]
Pour le point 1 il faut un hint pour sourcer et expliquer la démarche
