### ISSUE TITLE
Octokit::UnprocessableEntity in admin/communication/websites/pages#destroy

### ISSUE THREAD

**Issue by SebouChu** [osunyorg/admin#565]
## Error in Osuny

**Octokit::UnprocessableEntity** in **admin/communication/websites/pages#destroy**
PATCH https://api.github.com/repos/noesya/bordeauxmontaigne-ecoconception/git/refs/heads/main: 422 - Reference cannot be updated // See: https://docs.github.com/rest/reference/git#update-a-reference

[View on Bugsnag](https://app.bugsnag.com/noesya-1/osuny/errors/6374e4b08d8f53000894d03d?event_id=6374e4b000a152a62e830000&i=gh&m=ci)

## Stacktrace

    app/services/git/providers/github.rb:43 - push
    app/services/git/repository.rb:22 - sync!
    app/models/concerns/with_git.rb:63 - block in destroy_from_git
    app/models/concerns/with_git.rb:57 - each
    app/models/concerns/with_git.rb:57 - destroy_from_git
    app/models/concerns/with_git.rb:39 - destroy_and_sync
    app/controllers/admin/communication/websites/pages_controller.rb:83 - destroy
    app/controllers/application_controller/with_locale.rb:12 - switch_locale

[View full stacktrace](https://app.bugsnag.com/noesya-1/osuny/errors/6374e4b08d8f53000894d03d?event_id=6374e4b000a152a62e830000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by SebouChu** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Octokit::UnprocessableEntity** in **Communication::Website::Page#sync_with_git_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/6374e4b08d8f53000894d03d?event_id=63b54d2500a30867bd2a0000&i=gh&m=ra)

**Comment by SebouChu** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Octokit::UnprocessableEntity** in **Communication::Website::Page::EducationProgram#sync_with_git_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/6374e4b08d8f53000894d03d?event_id=63ba996000a2f05c170b0000&i=gh&m=ra)

**Comment by SebouChu** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Octokit::UnprocessableEntity** in **Communication::Website::Post#sync_with_git_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/6374e4b08d8f53000894d03d?event_id=6407349f00b8a8829ae30000&i=gh&m=ra)

**Comment by SebouChu** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Octokit::UnprocessableEntity** in **Communication::Website::Page::Person#sync_with_git_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/6374e4b08d8f53000894d03d?event_id=641f341300ba565c15160000&i=gh&m=ra)

**Comment by arnaudlevy** [comment]
Ce serait bien de logger les cas d'échec, pour pouvoir analyser quel fichier n'arrive pas à être traité.
@SebouChu est-ce que tu vois une solution pour améliorer le niveau d'info ?

**Comment by SebouChu** [comment]
Etant donné qu'on envoie 1 seul arbre pour l'ensemble des modifs, le débuggage est un peu compliqué, à explorer une fois l'opti des dépendances terminée

**Comment by SebouChu** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Octokit::UnprocessableEntity** in **Communication::Website::Menu#sync_with_git_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/6374e4b08d8f53000894d03d?event_id=6464e75800bd401186a80000&i=gh&m=ra)

**Comment by SebouChu** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**Octokit::UnprocessableEntity** in **Communication::Website::Menu#sync_with_git_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/6374e4b08d8f53000894d03d?event_id=6464e75b00bd3ba757050000&i=gh&m=fx)

**Comment by SebouChu** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**Octokit::UnprocessableEntity** in **Communication::Website::Page#sync_with_git_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/6374e4b08d8f53000894d03d?event_id=646b8c7400bd89c3e1f50000&i=gh&m=fx)

**Comment by SebouChu** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Octokit::UnprocessableEntity** in **Communication::Website#destroy_obsolete_git_files_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/6374e4b08d8f53000894d03d?event_id=646bc8bd00bd7f0504f60000&i=gh&m=ra)

**Comment by SebouChu** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Octokit::UnprocessableEntity** in **Communication::Website::Page#sync_with_git_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/6374e4b08d8f53000894d03d?event_id=6470d16600bd66ee9f670000&i=gh&m=ra)

**Comment by SebouChu** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**Octokit::UnprocessableEntity** in **Communication::Website#sync_indirect_object_with_git_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/6374e4b08d8f53000894d03d?event_id=647f56b800bde99a377a0000&i=gh&m=fx)

**Comment by SebouChu** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Octokit::UnprocessableEntity** in **Communication::Website#sync_indirect_object_with_git_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/6374e4b08d8f53000894d03d?event_id=647fa3e400be0282a9740000&i=gh&m=ra)

**Comment by SebouChu** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Octokit::UnprocessableEntity** in **Communication::Website#sync_indirect_object_with_git_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/6374e4b08d8f53000894d03d?event_id=6490610e00beb8f004ce0000&i=gh&m=ra)

**Comment by SebouChu** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Octokit::UnprocessableEntity** in **Communication::Website#sync_indirect_object_with_git_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/6374e4b08d8f53000894d03d?event_id=649d296100becb5bb3ab0000&i=gh&m=ra)

**Comment by SebouChu** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Octokit::UnprocessableEntity** in **Communication::Website::Page::Home#sync_with_git_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/6374e4b08d8f53000894d03d?event_id=64afe62000bebd70bd2f0000&i=gh&m=ra)

**Comment by SebouChu** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**Octokit::UnprocessableEntity** in **Communication::Website::Page#sync_with_git_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/6374e4b08d8f53000894d03d?event_id=64e62f6100bebcefa5a70000&i=gh&m=fx)

**Comment by SebouChu** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Octokit::UnprocessableEntity** in **Communication::Website#sync_indirect_object_with_git_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/6374e4b08d8f53000894d03d?event_id=64e8b6c400becbf1ac2b0000&i=gh&m=ra)

**Comment by SebouChu** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**Octokit::UnprocessableEntity** in **Communication::Website::Page#sync_with_git_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/6374e4b08d8f53000894d03d?event_id=64f58bcc00bed8c6ac510000&i=gh&m=fx)

**Comment by SebouChu** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Octokit::UnprocessableEntity** in **Communication::Website#sync_indirect_object_with_git_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/6374e4b08d8f53000894d03d?event_id=6501581200c591d450b70000&i=gh&m=ra)

**Comment by SebouChu** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**Octokit::UnprocessableEntity** in **Communication::Website::Post#sync_with_git_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/6374e4b08d8f53000894d03d?event_id=6516c32000c594f844670000&i=gh&m=fx)

**Comment by SebouChu** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Octokit::UnprocessableEntity** in **Communication::Website::Menu#sync_with_git_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/6374e4b08d8f53000894d03d?event_id=651b84b800c58d3ae48b0000&i=gh&m=ra)

**Comment by SebouChu** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**Octokit::UnprocessableEntity** in **Communication::Website::Post#sync_with_git_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/6374e4b08d8f53000894d03d?event_id=651d695d00c5890c365c0000&i=gh&m=fx)

**Comment by SebouChu** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Octokit::UnprocessableEntity** in **Communication::Website::Page#sync_with_git_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/6374e4b08d8f53000894d03d?event_id=65201c3d00c5aaf6f9430000&i=gh&m=ra)

**Comment by SebouChu** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**Octokit::UnprocessableEntity** in **Communication::Website::Page#sync_with_git_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/6374e4b08d8f53000894d03d?event_id=65201c3d00c5aaf6f9430000&i=gh&m=fx)

**Comment by SebouChu** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Octokit::UnprocessableEntity** in **Communication::Website#destroy_obsolete_git_files_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/6374e4b08d8f53000894d03d?event_id=6541197f00c7272b3c210000&i=gh&m=ra)

**Comment by SebouChu** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Octokit::UnprocessableEntity** in **Communication::Website::Page#sync_with_git_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/6374e4b08d8f53000894d03d?event_id=655c943600cd0954ef450000&i=gh&m=ra)

**Comment by SebouChu** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Octokit::UnprocessableEntity** in **Communication::Website::Menu#sync_with_git_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/6374e4b08d8f53000894d03d?event_id=656922e600ce15cc2cad0000&i=gh&m=ra)

**Comment by SebouChu** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Octokit::UnprocessableEntity** in **Communication::Website::Page::Home#sync_with_git_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/6374e4b08d8f53000894d03d?event_id=6573369900ce5c3b74b00000&i=gh&m=ra)

**Comment by SebouChu** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Octokit::UnprocessableEntity** in **Communication::Website#sync_indirect_object_with_git_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/6374e4b08d8f53000894d03d?event_id=657968a600ce54ac25710000&i=gh&m=ra)

**Comment by SebouChu** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Octokit::UnprocessableEntity** in **Communication::Website::Page::Home#sync_with_git_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/6374e4b08d8f53000894d03d?event_id=6594161200cfef7338940000&i=gh&m=ra)

**Comment by SebouChu** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**Octokit::UnprocessableEntity** in **Communication::Website::Page::Home#sync_with_git_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/6374e4b08d8f53000894d03d?event_id=65b528d700d280bf35440000&i=gh&m=fx)

**Comment by SebouChu** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Octokit::UnprocessableEntity** in **Communication::Website::Page#sync_with_git_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/6374e4b08d8f53000894d03d?event_id=65ba66af00d2801e5b230000&i=gh&m=ra)

**Comment by SebouChu** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Octokit::UnprocessableEntity** in **Communication::Website::Page::Home#sync_with_git_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/6374e4b08d8f53000894d03d?event_id=65c4dc7400d639aff4c30000&i=gh&m=ra)

**Comment by SebouChu** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Octokit::UnprocessableEntity** in **Communication::Website::Page#sync_with_git_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/6374e4b08d8f53000894d03d?event_id=65de02cb00da1ed146510000&i=gh&m=ra)

**Comment by SebouChu** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Octokit::UnprocessableEntity** in **Communication::Website::Page#sync_with_git_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/6374e4b08d8f53000894d03d?event_id=65ec9c6400dd735e5cfd0000&i=gh&m=ra)
