### ISSUE TITLE
Noms des fichiers téléchargeables

### ISSUE THREAD

**Issue by Olivia206** [osunyorg/admin#766]
Problème d'accessibilité avec la consultation des fichiers via les sites : les titres des pages (cf. screen) n'affichent pas le nom du fichier.

![Capture d’écran 2023-01-25 à 14 10 47](https://user-images.githubusercontent.com/91660674/214582634-b7751e51-a9fd-40d5-a069-7fb031105b28.png)

[Page de l'IUT concernée](https://www.iut.u-bordeaux-montaigne.fr/mentions-legales/) | [Fichier](https://osuny.s3.fr-par.scw.cloud/zgrer6to39wf1f1lbsqwzs0wmrjb?response-content-disposition=inline%3B+filename%3D%22Statuts_IUT.pdf%22%3B+filename*%3DUTF-8%27%27Statuts_IUT.pdf&response-content-type=application%2Fpdf)

**Comment by arnaudlevy** [comment]
Je sais pas comment on résout ça, c'est un lien keycdn

**Comment by Olivia206** [comment]
Sur Mozilla, le titre du fichier s'affiche bien
